---
title             : "ICMA 11/11"
shorttitle        : "Title"

author: 
  - name          : "Albert Sebastian"
    affiliation   : "Rutgers"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
    role: 
      - "Conceptualization"
      - "Writing - Original Draft Preparation"
      - "Writing - Review & Editing"
  - name          : "Ernst-August Doelle"
    affiliation   : "1,2"
    role:
      - "Writing - Review & Editing"
      - "Supervision"

affiliation:
  - id            : "1"
    institution   : "Wilhelm-Wundt-University"
  - id            : "2"
    institution   : "Konstanz Business School"

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  Add your abstract here.

keywords          : "keywords"
wordcount         : "X"

bibliography      : "zoteroLibrary.bib"

floatsintext      : no
linenumbers       : yes
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

classoption       : "man"
output            : papaja::apa6_pdf
bibliography: references.bib
---

```{r setup}
library("papaja")
library("tidyverse")
library("ggplot2")
library("readr")
library("dplyr")
r_refs("zoteroLibrary.bib")

# Global chunk options
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE
)

```

```{r}
r_refs(file = "zoteroLibrary.bib")
my_citations <- cite_r(file = "zoteroLibrary.bib")
```

```{r theme setup}
theme_set(theme_minimal())
theme_update(
  plot.title = element_text(hjust = 0.5),
  legend.position = "right"
)

```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

# Methods

We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis

We used `r cite_r("zoteroLibrary.bib")` for all our analyses.

# Results

# Discussion

\newpage

# [@adipose]References

::: {#refs custom-style="Bibliography"}
:::
